### ISSUE TITLE
Breno - Evento

### ISSUE THREAD

**Issue by brambati** [meeventos/api-meeventos-js#3]
**Criar rotas e lógica para o gerenciamento de eventos**

1. **Descrição:** Implementar a funcionalidade para listar e detalhar eventos. A lógica deve permitir a futura inclusão de criação, edição e remoção de eventos.

2. **Tarefas:**

- [x]  Implementar rota GET /{empresa}/api/v1/events para listar todos os eventos da empresa.
- [x]  Implementar rota GET /{empresa}/api/v1/events/{id} para exibir os detalhes de um evento específico.
- [x]  Escrever testes para validar o comportamento das rotas de eventos.

**Comment by thallesbrandao** [comment]
@Aprovei
